### ISSUE TITLE
Making an element a @container messes with the width of the component

### ISSUE THREAD

**Issue by alexander-densley** [tailwindlabs/tailwindcss-container-queries#29]
### What version of @tailwindcss/container-queries are you using?

0.1.1

### What version of Node.js are you using?

21.4

### What browser are you using?

arc with chromium

### What operating system are you using?

mac02

### Reproduction repository

https://github.com/alexander-densley/permitify

### Describe your issue

when I make an element a container, it seems to reduce the element to its min-width. confused as to how to use these if this is the expected behavior. would love any advice.

https://github.com/user-attachments/assets/2c16e886-a3e7-45f4-bd4b-113c6b938040

**Comment by alexander-densley** [comment]
for context, there are no other uses of container in my code, i just noticed this behavior when I started trying to use it

**Comment by ericbf** [comment]
That’s expected because of how containers work in HTML/CSS. Any CSS `container` cannot take its width from its children. It must have its width derived regardless of children sizes. See [this note about inline-size](https://developer.mozilla.org/en-US/docs/Web/CSS/container-type#inline-size).

This is not related to this plugin, it’s just how CSS Containers work.

**Comment by alexander-densley** [comment]
@ericbf thanks!
